import type { DemoInterest } from './public-demo-context';
export const PUBLIC_MODULES: Array<{ key: DemoInterest; title?: string; body?: string; route: string; group: 'Assess' | 'Protect' | 'Operate' | 'Assets' }> = [
  { key: 'gap', route: '/gap-analysis', group: 'Assess' },
  { key: 'grc', title: 'risksScreen', body: 'grcDesc', route: '/riscos', group: 'Assess' },
  { key: 'controls', route: '/governanca/controles', group: 'Assess' },
  { key: 'audits', route: '/governanca/auditorias', group: 'Assess' },
  { key: 'privacy', body: 'privacyDesc', route: '/privacidade', group: 'Protect' },
  { key: 'thirdParties', body: 'thirdPartiesDesc', route: '/due-diligence', group: 'Protect' },
  { key: 'channel', body: 'channelDesc', route: '/denuncia', group: 'Protect' },
  { key: 'incidents', route: '/incidentes', group: 'Protect' },
  { key: 'continuity', route: '/continuidade', group: 'Protect' },
  { key: 'dashboard', route: '/dashboard', group: 'Operate' },
  { key: 'actions', route: '/planos-acao', group: 'Operate' },
  { key: 'projects', route: '/projetos', group: 'Operate' },
  { key: 'documents', route: '/documentos', group: 'Operate' },
  { key: 'contracts', route: '/contratos', group: 'Operate' },
  { key: 'reports', route: '/relatorios', group: 'Operate' },
  { key: 'assets', route: '/ativos', group: 'Assets' },
  { key: 'licenses', route: '/ativos/licencas', group: 'Assets' },
  { key: 'keys', route: '/ativos/chaves', group: 'Assets' },
  { key: 'systems', route: '/sistemas', group: 'Assets' },
  { key: 'privileged', route: '/contas-privilegiadas', group: 'Assets' },
  { key: 'reviews', route: '/revisao-acessos', group: 'Assets' },
  { key: 'settings', route: '/configuracoes', group: 'Operate' },
];
